### PR TITLE
Switch to setuptools-scm

### PR DESCRIPTION
**Pull request by TimoRoth**
See Issue #727

### CODE REVIEW

**Comment by fmaussion** [comment]
Nice! This implies no new dependency, right?

**Comment by TimoRoth** [comment]
Only setuptools_scm and setuptools_scm_git_archive at setup time from how I understand it.

**Comment by fmaussion** [comment]
If I install your branch from git, I get: 

```
>>> import oggm
>>> oggm.__version__
'0.1.dev763+gb361915'
```

This doesn't seem right?

**Comment by TimoRoth** [comment]
My fork does not have any tags at all.
Or you didn't pull tags (git fetch --tags) in a very long time.

**Comment by fmaussion** [comment]
> My fork does not have any tags at all.

Yeah, probably this

**Comment by TimoRoth** [comment]
Pushed the tags from here to my fork as well now. Also, this is documented to not support anything else than 3 segment version schemes (major.minor.micro), but it seems to work just fine with v1.1 for all I can tell.

**Comment by fmaussion** [comment]
yeah, v1.1 was a mistake. Let's get v1.1.1 out soon ;-)

can we merge this?

**Comment by TimoRoth** [comment]
One advantage of omitting the micro version is that it titles master as 1.2-dev right now, which seems better if we want to release a 1.1.1 from the stable branch.

**Comment by fmaussion** [comment]
Let's move this discussion in another issues, I'd like to make a clear policy about this

**Pull request merged**
