### PR TITLE
Add DEM source information

### PR DESCRIPTION
**Pull request by matthiasdusch**
Every GlacierDirectory gets a file `dem_source.txt` where we specify the used DEM and advise the user how to cite it in publications. There were still some DEMs missing.

Also added a "Date of acquisition" to the source text. Could be used for #850 but for most DEMs this is a quite broad range of a decade or so...

### CODE REVIEW

**Comment by matthiasdusch** [comment]
also this lead to the blog post PR here https://github.com/OGGM/oggm.github.io/pull/78 which should be merged first to make sure the links in the source text work.

**Comment by fmaussion** [comment]
Thanks! I think we should tackle https://github.com/OGGM/oggm/issues/850 in this PR. Let's chat tomorrow about the way to go

**Comment by matthiasdusch** [comment]
> I think we should tackle #850 in this PR. 

Had an first attempt at this, but still WIP or at least thinking in progress...

**Comment by matthiasdusch** [comment]
in the previous commit I read the daterange and info from the dem_sources.txt template. Now I go for the actual dem_source.txt in the GDir which is more sensible I think.

**Pull request merged**
