### PR TITLE
Adds new functionalities to dynamic spinup

### PR DESCRIPTION
**Pull request by pat-schmitt**
In this PR I add two new options to the dynamic spinup function. First, you can now define an absolute precision to match in addition to a percentage value. And second, you can now define a minimum ice thickness, for filtering out potential seasonal spikes.
Let's see if all tests pass!

- [ ] Tests added/passed
- [ ] Fully documented
- [ ] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by pat-schmitt** [comment]
Oh, I just realized that PyCharm's pep8 auto-formatting has changed some lines in the file test_models. Is it possible to exclude them during merging or should I redo all changes by hand?

**Comment by fmaussion** [comment]
It's fine thanks!

**Comment by fmaussion** [comment]
looks good, right? ready to merge?

**Comment by pat-schmitt** [comment]
Yes in principle it is ready. But I already started the prepro runs on the cluster, so we can wait until this is finished and analysed.

**Comment by pat-schmitt** [comment]
If all test passes this PR is ready to merge.

**Comment by fmaussion** [comment]
@pat-schmitt your current developments are independent of this branch right? can I merge this?

**Pull request merged**
