### PR TITLE
Minor tweaks to compile climate output

### PR DESCRIPTION
**Pull request by fmaussion**
This just suppresses the warnings and makes sure we close the files for windows.

### CODE REVIEW

**Comment by fmaussion** [comment]
No that I had time to think about it, I am not so sure anymore that the time format is the correct one: in the compiled output files from the models, the time is in float years (as it is here), but it is in hydrological years! (i.e. float year 1901.00 means 01/10/1901).

I'm not sure yet what is best. For now we keep it like this, maybe you'll be able to make a better decision when you use the data @anoukvlug

**Comment by fmaussion** [comment]
Yes, I think we shoud keep the same format for consistency with the other outputs, but convert it to hydro years too. Let's talk about it tomorrow

**Comment by anoukvlug** [comment]
Thanks for making the changes.

I agree that the times should have the same format. I think floating hydrological years can be a bit confusing. What would be the reason to not save regular floating years?

**Comment by fmaussion** [comment]
> I think floating hydrological years can be a bit confusing. What would be the reason to not save regular floating years?

Because hydrological years are the convention in glaciology (the reference MB data is stored this way). All years you have looked at are already hydrological years -- I think this is also how @bmarzeion is doing it. 

I *really* should make this clear in the files attribute though -- this is very error prone (actually now that I think of it there are maybe even a few bugs in the codebase due to this)

**Comment by fmaussion** [comment]
Will do this in a separate PR

**Comment by bmarzeion** [comment]
Yes, hydrological years are necessary for the validation etc., and also for hydrological applications. But I agree that they are a pain when it comes to sea level questions etc - which are global (tow different hydrological years on two hemispheres!) and where no one cares about hydrology. I think ultimately we should provide monthly outputs - and then make sure we look at the correct differences for the applications we are using OGGM for.

**Comment by fmaussion** [comment]
> two different hydrological years on two hemispheres

Is it so? Are you using different definitions for the two hemispheres? Currently we do October-Sept everywhere

**Comment by bmarzeion** [comment]
Yes, I'm using April to March in the Southern Hemisphere.

**Comment by fmaussion** [comment]
:( definitely not the best news for a Sunday evening. Why did I not know this? Are the WGMS data defined this way?

**Comment by bmarzeion** [comment]
I think so - but I was using Graham's collection for validation, so I'm not entirely sure for WGMS. But it would make sense, wouldn't it?

**Comment by fmaussion** [comment]
I had a look, and information about this is quite buried in the database itself (`E-MASS-BALANCE-OVERVIEW.csv`), where *some* glaciers provide information about "their" definition of Winter and Annual MB. Indeed, most glaciers in the SH are from April to March :(

I'll have a look about how to implement this in OGGM. It's a small thing, but still a bit annoying ;)

**Pull request merged**
