### PR TITLE
make merged glaciers use original DEM source

### PR DESCRIPTION
**Pull request by matthiasdusch**

### CODE REVIEW

**Comment by fmaussion** [comment]
Why is this necessary? I think that this should not need a change

**Comment by matthiasdusch** [comment]
the rgi_id of merged glaciers has a '_merged' suffix which can not be found in the new DEM_SOURCE_TABLE. Another solution would be to exclude such suffixes within `default_dem_source`

**Comment by matthiasdusch** [comment]
first idea opened a can of worms including user specified DEM paths like those during testing.

So I propose this simpler fix which just assures that no rgi_id suffixes are considered at `default_dem_source`

**Review by fmaussion — APPROVED** [review]
That's better I think!

**Pull request merged**
