### PR TITLE
fix bug: core/gis.py: use non-existent topo_valid_mask key from nc.variables

### PR DESCRIPTION
**Pull request by 8fdafs2**
solution: delete the related line

### CODE REVIEW

**Comment by TimoRoth** [comment]
On 15.01.2021 11:55, 8fdafs2 wrote:
> solution: delete the related line

I'm not sure how that is a solution.
That variable is used in the function, and just removing it is going to 
cause issues further down the line.

**Comment by fmaussion** [comment]
Are there some bots that do this kind of stuff in PRs?

If yes, why would someone use such a bot?

**Comment by 8fdafs2** [comment]
> 
> 
> Are there some bots that do this kind of stuff in PRs?
> 
> If yes, why would someone use such a bot?

I have to admit it's a reckless PR, but not a bot here.

**Comment by 8fdafs2** [comment]
> 
> On 15.01.2021 11:55, 8fdafs2 wrote: solution: delete the related line
> I'm not sure how that is a solution. That variable is used in the function, and just removing it is going to cause issues further down the line.

I apologize it's reckless PR. I totally ignored the use of 'valid mask' in the following lines.
The reason why I removed this line is that there are some KeyError threw at the removed line as the key 'topo_valid_mask' doesn't exist at that moment and the issue seems to get 'solved' after the removal of that line.

**Comment by 8fdafs2** [comment]
This PR is not a solution but I suspect the issue I mentioned above might be a real one.

**Pull request closed without merging**
