### PR TITLE
Switch from urllib to requests for downloads

### PR DESCRIPTION
**Pull request by TimoRoth**
This should hopefully fix the certificate issues once and for all.

### CODE REVIEW

**Comment by fmaussion** [comment]
closes https://github.com/OGGM/oggm/issues/462

**Comment by TimoRoth** [comment]
I didn't want to put that in, because I have no idea if it closes that specific issue. Will need testing on an affected system.

**Comment by fmaussion** [comment]
yes! Sorry

**Comment by fmaussion** [comment]
OK, salem should be on pypi now: https://pypi.org/project/salem/

**Comment by fmaussion** [comment]
It looks like the setup script will overwrite your docker container though. Why is that so?

The docker probably has a version called 0.2.1+fajfaljkfa : doesn't that count as `>` ? Maybe ``>=``?

**Comment by TimoRoth** [comment]
We have a custom pip command to install latest salem from git in our travis script.
So setup.py will find the existing salem and be happy about it.

**Comment by fmaussion** [comment]
For some reason, salem is reinstalled by pip: 

```
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->oggm==1.0.2+9.gba2d6e9)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.6/dist-packages (from cligj>=0.4->fiona->oggm==1.0.2+9.gba2d6e9)
Requirement already satisfied: decorator>=4.1.0 in /usr/local/lib/python3.6/dist-packages (from networkx>=1.8->scikit-image->oggm==1.0.2+9.gba2d6e9)
Requirement already satisfied: toolz>=0.7.3; extra == "array" in /usr/local/lib/python3.6/dist-packages (from dask[array]>=0.9.0->scikit-image->oggm==1.0.2+9.gba2d6e9)
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python3.6/dist-packages (from botocore<1.11.0,>=1.10.37->boto3->oggm==1.0.2+9.gba2d6e9)
Installing collected packages: salem, oggm
  Found existing installation: salem 0.2.2-1-gb1ac94a
    Uninstalling salem-0.2.2-1-gb1ac94a:
      Successfully uninstalled salem-0.2.2-1-gb1ac94a
  Running setup.py develop for oggm
Successfully installed oggm salem-0.2.2
```

**Pull request merged**
