### PR TITLE
new viewfinderpanorama DEM files

### PR DESCRIPTION
**Pull request by JohannesUIBK**
Not finished yet

### CODE REVIEW

**Comment by fmaussion** [comment]
@JohannesUIBK , is this last commit now taking care of what we discussed last time?

**Comment by JohannesUIBK** [comment]
Indeed it is, I was just not able to test some things due to this GDAL/rasterio issue. But as I have seen now the dependcies should be fine, right? So maybe I can test this evening and then you can merge the PR! I will get back to you soon!

**Comment by JohannesUIBK** [comment]
Okay so I tried now to reinstall all Python packages from the conda forge channel, but I still cannot import rasterio properly somehow...consequently, I'm not really able to test if all the things work.
Does it work for you now?

**Comment by fmaussion** [comment]
OK. If you can reproduce the problem easily in a fresh environment it might be worth to report it to `conda-forge`, but no hurry (windows sucks anyway ;-) ). On a side note: we have no such problems on appveyor, which is also using a windows machine.

I will have to clone your branch to test it, I will have a look by the end of the week. Thanks!

**Comment by fmaussion** [comment]
OK, merging this now since tests are OK, will have a look at the details later today or tomorrow. Thanks @JohannesUIBK !

**Comment by JohannesUIBK** [comment]
Okay and thanks for both the tip concerning the report and for the merge!

**Pull request merged**
