### PR TITLE
Update test images

### PR DESCRIPTION
**Pull request by TimoRoth**
I'd expect those tests to still fail.
Opening this to have something tracking that issue.

### CODE REVIEW

**Comment by fmaussion** [comment]
@TimoRoth can you rebase and check again? Tests are green on master since https://github.com/OGGM/oggm/pull/1279

**Comment by TimoRoth** [comment]
You can just hit Re-Run on the checks, it should always run against current base branch with PR merged into it.

**Comment by TimoRoth** [comment]
I think the error changed, did it? Don't see it complaining about lon/lat anymore at least.

**Comment by fmaussion** [comment]
> You can just hit Re-Run on the checks, it should always run against current base branch with PR merged into it.

That's what I thought as well but the fixes I merged are still occurring.

**Comment by fmaussion** [comment]
For example, `KeyError: 'no index found for coordinate longitude'` happens because a `ValueError` became a `KeyError` in xarray, and is fixed in https://github.com/OGGM/oggm/pull/1279/files

**Comment by TimoRoth** [comment]
Makes me wonder if the PR Action needs fixed. It should be tested the merged PR.

**Comment by fmaussion** [comment]
> Makes me wonder if the PR Action needs fixed. It should be tested the merged PR.

Yes, but this is only when clicking on the button "re-run all tests" - repush worked fine.

**Comment by TimoRoth** [comment]
On 16.08.2021 10:16, Fabien Maussion wrote:
>     Makes me wonder if the PR Action needs fixed. It should be tested
>     the merged PR.
> 
> Yes, but this is only when clicking on the button "re-run all tests" - 
> repush worked fine.

Well, it was a rebase on the latest changes. So it seems like the tests 
run right on the PR branch, and not on the merged base.

**Pull request merged**
