### PR TITLE
Try to avoid random IO errors when writing to tar

### PR DESCRIPTION
**Pull request by fmaussion**
@TimoRoth an example of error happening on cluster: 

```
2020-08-05 09:57:38: oggm.workflow: Execute entity task gdir_to_tar on 3537 glaciers
Traceback (most recent call last):
  File "/work/fmaussion/71/oggm_env/bin/oggm_prepro", line 8, in <module>
    sys.exit(main())
  File "/work/fmaussion/71/oggm_env/lib/python3.7/site-packages/oggm/cli/prepro_levels.py", line 470, in main
    run_prepro_levels(**parse_args(sys.argv[1:]))
  File "/work/fmaussion/71/oggm_env/lib/python3.7/site-packages/oggm/cli/prepro_levels.py", line 222, in run_prepro_levels
    utils.base_dir_to_tar(l_base_dir)
  File "/work/fmaussion/71/oggm_env/lib/python3.7/site-packages/oggm/utils/_workflow.py", line 2855, in base_dir_to_tar
    tar.add(dirname, arcname=os.path.basename(dirname))
  File "/usr/local/pyenv/versions/3.7.8/lib/python3.7/tarfile.py", line 1949, in add
    recursive, filter=filter)
  File "/usr/local/pyenv/versions/3.7.8/lib/python3.7/tarfile.py", line 1941, in add
    with bltn_open(name, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/users/fmaussion/run_scripts/run_rgitopo/RGI62/b_010/L0/RGI60-12/RGI60-12.00/RGI60-12.00845.tar.gz'
srun: error: node06: task 0: Exited with exit code 1
srun: Terminating job step 71.0
```

This is truely random but happens quite often, at least once among the 19 RGI regions. It doesn't make sense because the file which is apparently "not there" should be created by the statement, so this has to be some OS or NFS issue not responding fast enough or something.

### CODE REVIEW

**Comment by TimoRoth** [comment]
What do you mean, should be created by the statement?
It's trying to read a file, which is a tar file, and trying to add it to another tar file?
The odd thing is, it seems like it goes into the isdir path in https://github.com/python/cpython/blob/v3.7.8/Lib/tarfile.py#L1949 which makes sense, but then a file it just enumerared from that dir apparently isn't there?

What confuses me a bit is why it's trying to tar up something from /home, while it's working in /work?

**Comment by fmaussion** [comment]
> What do you mean, should be created by the statement?
> It's trying to read a file, which is a tar file, and trying to add it to another tar file?

Yes sorry you are right.

> The odd thing is, it seems like it goes into the isdir path in https://github.com/python/cpython/blob/v3.7.8/Lib/tarfile.py#L1949 which makes sense, but then a file it just enumerared from that dir apparently isn't there?

Yes I did not try to make sense of these errors because they are random. Restarting the run could work for example.

> What confuses me a bit is why it's trying to tar up something from /home, while it's working in /work?

Yes, that's part of the `prepro_gdir` cli workflow: instead of writing the file locally I directly tar them on /home -> that's specific to this workflow though. Should I try differently?

**Comment by TimoRoth** [comment]
No, this should definitely work, just struck me as a bit odd.
I'll try changing some options on the NFS server.

**Comment by fmaussion** [comment]
You are right, it's an OS/NFS issue. It's trying to tar the entire `RGI60-12.00` directory, so `RGI60-12.00845.tar.gz` is not given by the python code, it's provided by the OS as being there but then erroring at writing.

**Pull request merged**
