### PR TITLE
Bring ela back as output variable

### PR DESCRIPTION
**Pull request by anoukvlug**
Some time ago the ELA was removed from the model_diagnostics.nc (#1145). This PR should make it possible again to get the ELA as an output. Different than before, computing the ELA will now be a separate entity tasks. This choice was made (#1145) because the ELA is a diagnostic variable.

The PR is not perfect and I'm open for feedback :) 

Closes https://github.com/OGGM/oggm/issues/#1328

- [x] Tests added/passed
- [ ] Fully documented
- [x] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by fmaussion** [comment]
Sorry I'm late to the party, but after some thoughs, please follow the same workflow model as

https://github.com/OGGM/oggm/blob/1e4283853e7fdcc79a64a39b62dc0d197460f178/oggm/utils/_workflow.py#L1526

ELA should work very much the same. Thanks!

**Comment by anoukvlug** [comment]
No worries and thank you for the advice :)

**Comment by fmaussion** [comment]
Excellent thanks! I have made a few suggestions - once this is added and the pep8 checks are corrected this is good to go!

**Comment by anoukvlug** [comment]
@fmaussion, thank you for the suggestions! From my side this PR is ready to be merged :)

**Comment by fmaussion** [comment]
Brilliant! Thanks a lot @anoukvlug

**Pull request merged**
