### PR TITLE
add bias option for run_from_climate_data()

### PR DESCRIPTION
**Pull request by juliaeis**
This change add an optional parameter for the bias in run_from_climate_data()

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks! Can you add the keyword argument to the docstring as well? See task above for an example.

**Comment by juliaeis** [comment]
sorry, for the unnecessary commits cause to wrong changes and spelling!

**Comment by fmaussion** [comment]
> sorry, for the unnecessary commits cause to wrong changes and spelling!

this is totally not important - we squash everything at merge anyway

**Comment by fmaussion** [comment]
Thanks @juliaeis !

**Pull request merged**
