### PR TITLE
Add sanity checks for water level of tidewater glaciers

### PR DESCRIPTION
**Pull request by fmaussion**
Closes https://github.com/OGGM/oggm/issues/954

This adds the sanity checks discussed in https://github.com/OGGM/oggm/issues/954

WIP:

- [x] Make the inversion calving a *default* workflow for the inversion
- [ ] Use 5 last pixels instead of last for inversion with calving (although I'm not sure about this one)
- [x] Tests added/passed
- [ ] Fully documented
- [x] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by fmaussion** [comment]
A nice side effect of this change: Coxe glacier (which had an "out-of-the box" free board of 95 meters) now has the max arbitrary free board of 50 meters. Before, the calving inversion was failing (no calving, meaning unphysical values), and with this change it now "calves"

This could be by chance (and other glaciers might get worse), but I'm quite confident that forcing the free-board within a given range (currently: 10 to 50 m) is a good thing.

cc @bearecinos @ehultee

**Comment by ehultee** [comment]
Nice.  This might burn you on really big glaciers, but it seems a good baseline.  What happens if the front retreats and exposes a freeboard >50 m?  More calving, dynamic advance and thinning, total implosion?  Or is this only for static inversion now?

Also, fwiw: looks like you implemented a new default lake-terminating freeboard of 10 m (in params.cfg) which is not reflected in the comments in flowline.py L1053-1055.

**Comment by fmaussion** [comment]
>  What happens if the front retreats and exposes a freeboard >50 m? More calving, dynamic advance and thinning, total implosion? Or is this only for static inversion now?

The latter - although the artifial initial water level which is used for the inversion (e.g. about 40 m for Coxe) is also used for the dynamical runs (this is consistent), but there is not physical/numerical limit on the free board anymore.

> Also, fwiw: looks like you implemented a new default lake-terminating freeboard of 10 m (in params.cfg) which is not reflected in the comments in flowline.py L1053-1055.

Thanks! I will check this + other aspects of the documentation today

**Comment by fmaussion** [comment]
also closes https://github.com/OGGM/oggm/issues/869

**Comment by fmaussion** [comment]
cc @jmalles if the tests pass I'll merge this as is. 

I don't have time to write a comprehensive documentation yet but I'll revisit the example notebook to take these changes into account. Basically the main changes are:
- there is now a water_level variable used here and there to make calving less crazy when DEMs our outlines are bad 
- we report volume below water and other calving related diagnostics in the compile_* files
- calving is switched on per default, but you still have to manually run the calving inversion to use it in the inversion

**Comment by fmaussion** [comment]
OK, in it is. Let's cross fingers that not too many bugs are hidden in there

**Pull request merged**
