### PR TITLE
Make execute_entity_task forward kwargs

### PR DESCRIPTION
**Pull request by TimoRoth**
Without this it's impossible to call for example distribute_thickness, which needs the how parameter to be set to do anything.

### CODE REVIEW

**Comment by fmaussion** [comment]
:+1: this is great. I thought I had implemented this already but obviously not!

I 'm not sure if you need your own decorator for this though, [functools.partial](https://docs.python.org/3.5/library/functools.html#functools.partial) should do the trick?

The failing tests are unrelated.

**Comment by TimoRoth** [comment]
functools.partial is only pickleable in python3, so in python2 passing it to map fails.

**Comment by fmaussion** [comment]
OK. Can you add a comment line in the `_pickle_copier` class to document this so we can remember in the future?

I am starting to think that we should drop python2 support as a whole (http://python3statement.github.io/ )

**Comment by TimoRoth** [comment]
Comment added.

Yes, dropping python2 support would definitely simplify the code in a lot of places, and speed up builds.

**Comment by fmaussion** [comment]
Thanks! We will drop python 2 support soon (shouldve done it in the first place already :( )

**Pull request merged**
