### PR TITLE
Get ready for numerical tests

### PR DESCRIPTION
**Pull request by fmaussion**
A follow up to https://github.com/OGGM/oggm/issues/909 

With these tools, we can now compare various numerical schemes against each other in realistic settings.

For Alex's scheme, we need to make all bed shapes rectangular (which is OK), but we also need to make all sections the same widths (this is a bit more annoying) -> @alexjarosch , could your scheme accept varying widths along the flowline?

### CODE REVIEW

**Comment by fmaussion** [comment]
(I'm not going to merge this btw, this is just to get the ball rolling).

**Comment by alexjarosch** [comment]
> For Alex's scheme, we need to make all bed shapes rectangular (which is OK), but we also need to make all sections the same widths (this is a bit more annoying) -> @alexjarosch , could your scheme accept varying widths along the flowline?

My scheme, as all diffusion type flowline schemes computes ice fluxes (vertically integrated velocities and knows flux gate geometries) on grid cell boundaries along the flow line geometry. You can of course recover the actual average velocity on each grid cell boundary and use this to estimate a total ice flux across a flow perpendicular cross section with methods similar to the ones OGGM uses already.

However be aware that flowline models like my scheme only see the drag (or better shear stress) from the basal boundary, they assume laterally infinite domains. Your scheme ignores the lateral shear stresses due to side walls as well if I remember correctly. This will make a comparison more difficult.

Something we should discuss in more detail.

**Comment by fmaussion** [comment]
Could we put the width in the diffusion equation as Oerlemans 97 does? 

> Your scheme ignores the lateral shear stresses due to side walls as well if I remember correctly. 

In default configuration yes, but Philipp implemented a parameterization after [Adhikari and Marshall](https://www.cambridge.org/core/journals/journal-of-glaciology/article/parameterization-of-lateral-drag-in-flowline-models-of-glacier-dynamics/9C5836F192CE16F10F08DE750B1BFCAE). But people usually don't turn this on.

> Something we should discuss in more detail.

I'd be glad to chat shortly about this yes

**Comment by alexjarosch** [comment]
> Could we put the width in the diffusion equation as Oerlemans 97 does?
 
Yes you can. However if it actually will make sense is a **serious** question here.

The misunderstanding lies in what the variable "S" means in OGGM and in the MUSCL-Superbee scheme.

- For OGGM "S" is the cross sectional area of the whole glacier, following Oerlemans ideas...
- In MUSCL-Superbee (as in all diffusion type SIA models), "S" or "s" as I wrote in my paper is the surface elevation. This stems from the fact that the mass conservation equation (e.g. [OGGM docs, frist equation](https://docs.oggm.org/en/latest/ice-dynamics.html) is valid for a "control volume", in which "U" (the velocity) then gets integrated vertically and so... (Derivation of the sallow ice equations, or shallow water equations for that matter). Actually the derivation is for &part; h / &part; t and one can make &part; s/ &part; t out of it by assuming a constant bed elevation b and h = s-b.

Now if you use just one control volume across the glacier, as OGGM and Oerlemans does/did, you run into issues with the side walls, as they create boundary conditions. Given one control volume across the glacier for this case means that you want to calculate on one point the average velocity "u" (in the OGGM sense) where the lateral side walls of that control volume are at u=0 (or prescribed sliding velocity), however the average should be different from u=0. You see the issue here, right?

So, sparing us a long discussion on the numerics of this setup, I would suggest you go the other way for a comparison. Why not recover the central flow line ice flux or centerline vertical ice velocity from your "flux-based" scheme and then compare to the MUSCLSuperbee. This way you skip the parametrization of any lateral boundary conditions and actually compare two results that are comparable. 
 
> I'd be glad to chat shortly about this yes

You let me know.

**Pull request closed without merging**
