### PR TITLE
AWS install packages for OGGM

### PR DESCRIPTION
**Pull request by fmaussion**
`node_install` now has options to install the packages if needed. After install the AWS instance can run oggm without error, in python3. 

pip install takes 10 to 20 minutes, I think we can do better if we use wheels

@fso42 , @TimoRoth for you to review and merge if found useful

### CODE REVIEW

**Comment by fmaussion** [comment]
I alsoslightly changed the defaults to force a username. This makes it less easy to do wrong manips (as I just did)

**Comment by TimoRoth** [comment]
First, I would setup the VirtualEnv in /work, if it's available.
That way there is no need to run the 20 minute Virtualenv-Setup every time.

Also, I'd prefer to have the setup sequence in a separate task, so it can be run individually on machines that still need it.

**Comment by TimoRoth** [comment]
If you don't mind, i can do the necessary changes.

**Comment by fmaussion** [comment]
Perfect! Yes, please, modify it and make it better! I'll merge this one so that you can go on from that

**Comment by fmaussion** [comment]
Ha, and also if you have time could you look at this one? https://github.com/OGGM/oggm/issues/55

**Pull request merged**
