### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by anoukvlug**
This PR addresses issue #1555, by improving the error message that is being raised for the following error  `ModuleNotFoundError: No module named 'shapely.io'`.

### CODE REVIEW

**Comment by TimoRoth** [comment]
Is the new notebook part of this PR intentionally?
Also, the text of the error message can change depending on the python version. And maybe even system language?
Much better to check the name property of the exception instead.

**Comment by anoukvlug** [comment]
Yes, that does make sense. However I don't think I fully understand you suggestion. What do you mean with name property? 

Thanks for noticing the notebook, that was not supposed to be included in this PR.

**Comment by anoukvlug** [comment]
Thanks for the explanation @TimoRoth! Is the latest commit what you had in mind?

**Comment by TimoRoth** [comment]
To re-raise an exception, just call `raise` without any arguments. Otherwise you might obscure where the error actually came from.

One more issue I could see is that by creating a new ModuleNotFoundError without the name/path argument set, you might be breaking conventions.

What you could do instead:

```python
                if err.name == "shapely.io":
                    err.msg = "You need shapely version 2.0 or higher for this to work."
                raise
```

**Comment by anoukvlug** [comment]
Thanks for the coding lesson. That looks indeed better :)

**Comment by fmaussion** [comment]
Thanks!

**Pull request merged**
