### PR TITLE
Graphics plot fix

### PR DESCRIPTION
**Pull request by Keeptg**
Closes https://github.com/OGGM/oggm/issues/1238

- [x] Tests added/passed
- [x] Fully documented
- [x] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks!

Please change 

```
SAMPLE_DATA_COMMIT = 'b885e9acc48037a030decb7daf73d44b4398e5e1'
```

to 

```
SAMPLE_DATA_COMMIT = '647ca4f1cb3de4b4e58125a6543a1653ff3d4bed'
```

in `utils/_downloads.py`

After this the tests will fail again, but I will be able to download the correct images

**Comment by fmaussion** [comment]
Ok, now try again with `f71d75040cfe3f7b72ccb3b9b5ff8d67c5de628c` please ;-)

**Comment by Keeptg** [comment]
> Ok, now try again with `f71d75040cfe3f7b72ccb3b9b5ff8d67c5de628c` please ;-)

Haha, finally! Thanks for the help!

**Comment by fmaussion** [comment]
Thanks!

**Pull request merged**
