### PR TITLE
Report download progress

### PR DESCRIPTION
**Pull request by TimoRoth**
Makes long lasting downloads of data file a little less annoying.

### CODE REVIEW

**Comment by fmaussion** [comment]
Great! Could you also update the docs to take into account this new dependency?
 https://github.com/OGGM/oggm/blob/master/docs/installing-oggm.rst 
Is the progressbar graphical or text based?

**Comment by TimoRoth** [comment]
It's a text based wget-style progressbar:
53% |####################                                               |  20.4 MiB   2.5 MiB/s ETA:  0:00:07

**Comment by TimoRoth** [comment]
conda does not seem to have a package for progressbar2, only the old python2-only progressbar.
Updated the docs accordingly, optionally installing it via pip if desired.

**Comment by fmaussion** [comment]
Perfect! I am starting to think that `utils.py` would benefit from a little bit of refactoring, we'll keep this in mind for later

**Pull request merged**
