### PR TITLE
change dem_mask name and remove .properties file

### PR DESCRIPTION
**Pull request by matthiasdusch**
glacier_mask might be a better name than dem_mask

also, if oggm_prepro is run with the docker container in singularity, it creates a weird `outlines.tar.gz.properties`. Let's remove that before packing up because that are 200k less files.

### CODE REVIEW

**Comment by matthiasdusch** [comment]
document for future:
I first thought the tar.gz.properties file is from compressing while creating it. But I am pretty sure now it's from reading the compressed shapefile. And it is most likely created by either Geopandas or Fiona. A bit hard to track as this only happens with the packages used in the current docker-image.

**Comment by fmaussion** [comment]
> I first thought the tar.gz.properties file is from compressing while creating it.

OK then maybe we should suppress them at the tar creation step (for all tar.gz shapefiles)

**Comment by matthiasdusch** [comment]
> > I first thought the tar.gz.properties file is from compressing while creating it.
> 
> OK then maybe we should suppress them at the tar creation step (for all tar.gz shapefiles)

No, the file is not created while writing or compressing but later while reading the compressed shapefile. Here:
```
geometry = gdir.read_shapefile('outlines').geometry[0]
```

So this is done by either Geopandas or Fiona. Or most likely and more specific by some module which is used withing gpd/fiona to open the tar.gz file...

**Comment by fmaussion** [comment]
Yes, but it still ends up in the final tar file, because the outlines (but not the intersects) are read by your rasterio_glacier_masks task -> my point is that we should not write them down in tar.

OR, we suppress them at the gdir level which is the only point where we read these files.

**Comment by fmaussion** [comment]
> we suppress them at the gdir level which is the only point where we read these files.

Here:

https://github.com/OGGM/oggm/blob/75e2c9494d03e0c2fcfd4f835fff72a675c7c868/oggm/utils/_workflow.py#L1954

**Comment by matthiasdusch** [comment]
ah ok, now I get it. 

Right now I delete this file at the end of `rasterio_glacier_mask`. Suppressing it in the first place would be sensible but needs some digging. 

We could also check for it and delete it in the read_shapefile funktion (like you suggested, while I am writing this)
I didn't want to mess with these internals but I am happy to move the 4 lines of code to `_read_shapefile_from_path`

**Comment by fmaussion** [comment]
> I didn't want to mess with these internals but I am happy to move the 4 lines of code to _read_shapefile_from_path

Yes, let's do that

**Pull request merged**
