### PR TITLE
DOC: table for RGI attributes inside input data, FAQ: own RGI?

### PR DESCRIPTION
**Pull request by bearecinos**
Text still needs changes in the FAQ ... let me know if this is more or less what you where thinking @fmaussion .
Cheers

### CODE REVIEW

**Comment by nchampollion** [comment]
Maybe we should add a warning (as you said maybe in the FAQ) about the fact that OGGM/RGI modeling will be different than using OGGM with your own outlines, especially if you look at length changes.

**Comment by bearecinos** [comment]
Yes, I will probably push something along this line maybe I could also write a blog post about my reasons to merge the Columbia glacier... to highlight when for some cases users might look into doing this. I think a blog post might be more appropriate than a notebook and we can make a link from the FAQ and input data section...

**Comment by fmaussion** [comment]
@bearecinos yes this would be awesome!

**Comment by fmaussion** [comment]
@bearecinos how would you feel about restarting this PR once you have more time on a cleaner basis?

The steps would be:
- save your changes somewhere safe
- clean your local master once for all:
  - `git checkout master`
  - `git fetch upstream`
  - `git reset --hard upstream/master`  (cannot be reverted: replace with `git merge upstream/master` in normal workflow)
- start a new branch: `git checkout -b add_rgi_docs`
- rewrite your changes
- `commit -a -m "your commit message"`
- `git push origin add_rgi_docs`
- open a new PR

This is a generally *good* workflow to get clean PRs ;-) If your master is not polluted, no need for hard reset

**Comment by bearecinos** [comment]
yes @fmaussion I will do that ... and submit a PR with everything finish and clean repo ... sorry for the mess

**Pull request closed without merging**
