### PR TITLE
Switch back to coveralls

### PR DESCRIPTION
**Pull request by TimoRoth**
They have by now figured out how to use Github Actions, and given the overall unreliability of coveralls.io with constant random test-failures, preferring them seems the right choice to me.

Also gives the test image a bump.

### CODE REVIEW

**Comment by fmaussion** [comment]
What is the status of this? Is there something I need to do?

**Comment by BtbN** [comment]
From my end it's ready, but I was hoping to have it complete a round of tests before merging it.

**Comment by TimoRoth** [comment]
From my end it's ready, was just hoping for it to complete a round of tests before merging it.

**Comment by fmaussion** [comment]
OK thanks. I'll push to your branch to address the remaining failures. Very annoying again

**Comment by fmaussion** [comment]
@TimoRoth `untested_base:20200720` won't make it because I needed to fix salem for upstream changes in matplotlib in  https://github.com/fmaussion/salem/pull/176

So either we wait for a new untested_base to be available with latest salem or we roll back to an older base version

**Comment by TimoRoth** [comment]
I've just told the Docker-Actions to build a new one. Should be available in an hour or two.

**Pull request merged**
