### PR TITLE
Add rectangle info to model section plot

### PR DESCRIPTION
**Pull request by fmaussion**

### CODE REVIEW

**Comment by TimoRoth** [comment]
I think since the latest Ubuntu update it does, yes.

Am 09.11.2017 um 17:13 schrieb Fabien Maussion:

**Comment by fmaussion** [comment]
Arg - I have no way to update the baselines myself then. Or maybe on the cluster?

**Comment by TimoRoth** [comment]
The cluster is also using freetype 2.8, so it will use and generate for 
the alt directory there.

I also feel like alt is a horrible name, and we should rename them to 
indicate that they are for different freetype versions, which is now 
seamlessly possible with the pinned commit being used.

Am 09.11.2017 um 22:39 schrieb Fabien Maussion:

**Comment by fmaussion** [comment]
> I also feel like alt is a horrible name, and we should rename them 

Agreed ;)

**Pull request merged**
