### PR TITLE
Downloading preprocessed GDirs with multiprocessing fails

### PR DESCRIPTION
**Pull request by matthiasdusch**
As preprocessed GDirs are regionally grouped, downloading two or more GDirs from one region will cause a `DownloadVerificationFailedException` if multiprocessing is enabled: If the file is not already downloaded, the first entity task will start downloading it, while the subsequent tasks see the existing but only partially downloaded file and will raise the above error.

This PR implements a multiprocessing Lock structure, following other download functions.

There might be smarter/faster ways to improve this in near feature.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks! 

> There might be smarter/faster ways to improve this in near feature.

yeah there is room for refactoring - this has all grown organically and is now a mess of duplicated code... :-(

**Comment by fmaussion** [comment]
It seems this breaks travis quite badly - maybe at the download of the sample data already?

**Comment by matthiasdusch** [comment]
Travis times out after 10min during initialization. Seems like locking `oggm_urlretrieve` and therefor downloading all files sequentially takes to much time.
To be honest I did not realize the tests so heavily depend on this function.

I'll think about a solution.

**Comment by fmaussion** [comment]
Thanks a lot @matthiasdusch !!!

**Pull request merged**
