### PR TITLE
an idea for processing ERA-5 and CERA-20C

### PR DESCRIPTION
**Pull request by anoukvlug**
This PR is a follow up on issue #930. It's not ready to be merged yet, but can be used as a base to discuss the implementation of processing ERA data for OGGM further.

- [ ] Tests added/passed
- [ ] Fully documented
- [ ] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by anoukvlug** [comment]
@fmaussion, I was wondering, shall I remove this PR or update it with a version of that computes the scaled anomalies with respect to CRU?

**Comment by fmaussion** [comment]
Hi @anoukvlug , sorry for not getting back to you.

I have very similar code in the pipeline right now, so I think we won't merge this as is. You should keep this code for your purpose of course!

Please leave this PR open in the time being, and I'll get back to you when I manage to get the new ERA code working.

In short, my work in progress aims at being able to mix all kinds of climate data together (ERA5 with CRU as reference, CRU with ERA5 as reference, etc.)

**Comment by anoukvlug** [comment]
No worries. It sounds like a you're working on a great feature :)

**Comment by fmaussion** [comment]
Thanks again! Implemented in https://github.com/OGGM/oggm/pull/1015

**Pull request closed without merging**
