### PR TITLE
Fabfile Updates

### PR DESCRIPTION
**Pull request by TimoRoth**
Moves instance setup into separate task(s) and updates doc accordingly.
Also refactors some common tasks into reusable functions.

The install_env script is re-purposed into a generic install script that can be used in any environment where pip is available.

### CODE REVIEW

**Comment by fmaussion** [comment]
Great, thanks! Is the install_env script still necessary btw?

**Comment by BtbN** [comment]
I left it in because it could be useful in case someone wants to setup a virtualenv outside of AWS, it's otherwise unused for now.

**Comment by TimoRoth** [comment]
I left it in because it could be useful in case someone wants to setup a virtualenv outside of AWS, it's otherwise unused for now.

**Comment by fmaussion** [comment]
Yes good idea. Merging this, thanks!

**Pull request merged**
