### PR TITLE
Fix rasterio deprecation warnings

### PR DESCRIPTION
**Pull request by TimoRoth**
See https://github.com/mapbox/rasterio/issues/86 for reference.
Fixes a couple hundred deprecation warnings that come up during testing.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks!

**Comment by fmaussion** [comment]
With rasterio > 1.0 this change is not desired. I get plenty of warnings:

```
/home/mowglie/disk/Dropbox/HomeDocs/git/oggm-fork/oggm/utils.py:1802: DeprecationWarning: 'src.affine' is deprecated.  Please switch to 'src.transform'. See https://github.com/mapbox/rasterio/issues/86 for details.
```

Will revert in an upcoming PR, or add a check for the rasterio version

**Comment by TimoRoth** [comment]
Rasterio 1.0 is not released yet, it's in alpha. So this should not be showing up normally. At least pip does not install rasterio 1.0 unless explicitly requesting pre-release versions.

This deprecation back and forth and renaming is a bit odd of them. The only way to consistently not get warnings seems to be to use a version check...

**Comment by fmaussion** [comment]
Yes: https://mapbox.github.io/rasterio/topics/migrating-to-v1.html

**Comment by fmaussion** [comment]
Will add a check for rasterio, but I favor 1.0 on my environments - the alpha has been around quite a while now, I wonder when they will release it

**Pull request merged**
