### PR TITLE
assure FlowlineModel step does not cross years.

### PR DESCRIPTION
**Pull request by matthiasdusch**
- [x] Tests added/passed
- [x] Fully documented
- [x] Entry in `whats-new.rst` 

Right now this PR is mainly to supplement the discussion in #710

### CODE REVIEW

**Comment by fmaussion** [comment]
@matthiasdusch did you make any more modifs on this? 

I'd like to have a look today and might push to your branch

**Comment by matthiasdusch** [comment]
no, no changes. Feel free to push

**Comment by fmaussion** [comment]
OK, I think this looks good like this. I will merge after a 1.1.1 release, because this needs to go in 1.2

**Comment by matthiasdusch** [comment]
yes, looks good. I like the implementation within `run_until` instead of `step`.

**Pull request merged**
