### PR TITLE
an attempt to make compiling files faster

### PR DESCRIPTION
**Pull request by anoukvlug**
This PR is a draft of an attempt to speed up the compiling of climate files and run_output files. 

Closes https://github.com/OGGM/oggm/issues/751 & https://github.com/OGGM/oggm/issues/752 & https://github.com/OGGM/oggm/issues/837

- [x] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by anoukvlug** [comment]
@fmaussion could you have a look at what you think of this PR?

**Comment by fmaussion** [comment]
Sorry for being so late on this one - this is very good work.

I will make a couple of changes if you agree: I'd like to simply use your method as default (i.e. not add a new task). I'll push on your branch if that's ok?

**Comment by anoukvlug** [comment]
No worries and yes, that is fine for me :)

**Comment by anoukvlug** [comment]
FYI: I didn't optimize the size (` lsubfiles `) of the temporary files that are being generated. I put it now as 1000 glaciers per temporary file. I think 1000 should be a good number, however there is probably a number that is more optimal.

**Comment by fmaussion** [comment]
OK @anoukvlug - I finally spent some time on this.

I have added some "python complexity" by using a decorator, but basically the idea is the same as yours. We need dask installed for the tests to run, so I can't merge right away.

I also deprecated `filesuffix` in favor of `input_filesuffix` -> your code will still work, but OGGM will raise a warning.

**Comment by anoukvlug** [comment]
Thanks @fmaussion for improving this PR!

**Comment by fmaussion** [comment]
Thanks @anoukvlug ! And sorry this took so long...

**Comment by anoukvlug** [comment]
No worries and thank you!

**Comment by fmaussion** [comment]
Let me know it you encounter any problem

**Pull request merged**
