### PR TITLE
Update test image

### PR DESCRIPTION
**Pull request by TimoRoth**
Next attempt, maybe tests succeed now.

### CODE REVIEW

**Comment by fmaussion** [comment]
I can't reproduce this locally with the following versions:

```
# OGGM environment: 
## System info:
    python: 3.8.5.final.0
    python-bits: 64
    OS: Linux
    OS-release: 5.4.0-58-generic
    machine: x86_64
    processor: x86_64
## Packages info:
    oggm: 1.3.2.dev124+ga91f577.d20201228
    numpy: 1.19.2
    scipy: 1.5.2
    pandas: 1.1.2
    geopandas: 0.8.1
    netCDF4: 1.5.4
    matplotlib: 3.3.2
    rasterio: 1.1.8
    fiona: 1.8.17
    pyproj: 3.0.0.post1
    shapely: 1.7.1
    xarray: 0.16.1
    dask: 2.27.0
    salem: 0.3.3-1-gb27b59c
```

Can I have a list of package versions so that I can double check?

**Comment by fmaussion** [comment]
Actually it could be nice to have a `print(utils.show_versions())` somewhere in the build log, no?

**Comment by TimoRoth** [comment]
You can list them via docker:
```
docker run --rm oggm/untested_base:20201220 bash -c "pip3 install git+https://github.com/OGGM/oggm.git && python3 -c 'import oggm.utils; print(oggm.utils.show_versions())'"
```

```
# OGGM environment:
## System info:
    python: 3.8.6.final.0
    python-bits: 64
    OS: Linux
    OS-release: 4.19.128-microsoft-standard
    machine: x86_64
    processor: x86_64
## Packages info:
    oggm: 1.3.2.dev126+g2d28279
    numpy: 1.19.4
    scipy: 1.5.4
    pandas: 1.1.5
    geopandas: 0.8.1
    netCDF4: 1.5.5.1
    matplotlib: 3.3.3
    rasterio: 1.1.8
    fiona: 1.8.18
    pyproj: 3.0.0.post1
    shapely: 1.7.1
    xarray: 0.16.2
    dask: 2020.12.0
    salem: 0.3.3-3-g3e8b770
    OGGM git identifier: e3b0389b807e3952940b06d017e373b829d111b2
```

**Comment by fmaussion** [comment]
Thanks! Still, having them in the github actions log would be great!

**Comment by fmaussion** [comment]
I can't reproduce any of this locally with the same package versions...

**Comment by fmaussion** [comment]
Maybe the rasterio wheels are broken or missing some lib or something?

**Comment by TimoRoth** [comment]
There's no wheels used in building the image.
Everything is built from source.

But I didn't see anything obviously wrong with any lib so far.

**Comment by fmaussion** [comment]
Could you push this to latest image to see if this disappeared by chance?

**Comment by TimoRoth** [comment]
On 20.01.2021 19:39, Fabien Maussion wrote:
> Could you push this to latest image to see if this disappeared by chance?

Sure, but not very hopeful on that, given that the images self-test is 
still failing.

**Comment by fmaussion** [comment]
Something in the image is broken, either in rasterio or PROJ. The following code is [from the rasterio documentation](https://rasterio.readthedocs.io/en/latest/topics/georeferencing.html#coordinate-reference-system):

```python
  profile = {'driver': 'GTiff', 'height': 100, 'width': 100, 'count': 1,
             'dtype': rasterio.uint8}
  with rasterio.open('/tmp/foo.tif', 'w', crs='EPSG:3857', **profile) as dst:
      pass 
```

it fails with:

```
>   ???
E   rasterio.errors.CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name

rasterio/_crs.pyx:281: CRSError
```

**Comment by fmaussion** [comment]
Maybe this? 

https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select

**Comment by TimoRoth** [comment]
I think this is just general chaos of proj and python packages...

pyproj comes with its version of libproj, and hard-required proj >=7.2.
Then gdal pulls a quite old version of proj from the system, along with 
its data.
Those two libraries then get mixed up and everything becomes a giant mess.
The SQL error happens because the old proj version gdal is using tries 
to read the data file of the modern proj version pyproj brings.
How the two end up reading each others files? I have no idea.

**Comment by fmaussion** [comment]
All green! What did you change?

**Comment by TimoRoth** [comment]
On 21.01.2021 08:09, Fabien Maussion wrote:
> All green! What did you change?

I stopped installing gdal via Ubuntu, and instead compile it and proj 
manually.
The Ubuntu version pulls in a really old proj version via apt, while 
pyproj comes with its own, much more recent, version of the library.

That way, other packages using proj (namely, gdal via rasterio) end up 
with a wild mix of library version and accompanying data files.
The data files are not compatible in either direction, hence the missing 
column in the table when pyprojs proj 7.2 tries to read the old proj 6 
data files or vice versa.

Now there is only a single proj library in the image, avoiding that 
issue, at the cost of a more complex Dockerfile and much longer build time.

**Comment by fmaussion** [comment]
Thanks Timo!

**Pull request merged**
