### PR TITLE
some additions to copy files

### PR DESCRIPTION
**Pull request by anoukvlug**
This pull request addresses issue #467.

1. It adds copying cesm_data files to the option 'inversion' and 'run' of the copy_to_basedir function.
2. It adds an entity task for copying files with the copy_to_basedir function.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks a lot! Actually, I think that making an entity task out of it makes much sense. 

Could you move the entire code to the task? I.e. the ``gdir.copy_to_basedir`` method should be deleted, and instead the task should contain all the code (this would be very similar code, but with ``gdir`` instead of ``self``). This might brake some tests, so you'll have to adapt them too.

That would be great!

**Comment by anoukvlug** [comment]
Yes, I just did. Thanks for the instructions! I will update my PR in a bit :)

**Comment by fmaussion** [comment]
This is excellent job, thanks! One last thing: can you add a short description of your change in [whats-new.rst](https://github.com/OGGM/oggm/blob/master/docs/whats-new.rst)? It is a small but breaking change, so it should be documented in the "breaking change" section

**Comment by anoukvlug** [comment]
Thanks :) Yes, I can add some documentation to [whats-new.rst](https://github.com/OGGM/oggm/blob/master/docs/whats-new.rst) today . 

I was wondering, when I click on the issues and pull requests on the [whats-new.rst](https://github.com/OGGM/oggm/blob/master/docs/whats-new.rst) page these don't work as a link, is it supposed to be like that?

**Comment by fmaussion** [comment]
> I was wondering, when I click on the issues and pull requests on the whats-new.rst page these don't work as a link, is it supposed to be like that?

Yes, they are rendered by sphinx when building the documentation. See: http://oggm.readthedocs.io/en/latest/whats-new.html

**Comment by anoukvlug** [comment]
That makes a lot of sense :)

**Comment by fmaussion** [comment]
Thanks!

**Pull request merged**
