### PR TITLE
Fix geopandas

### PR DESCRIPTION
**Pull request by pat-schmitt**
This is the first attempt to fix a bug with the updated Geopandas version.

- [x] Tests added/passed

### CODE REVIEW

**Comment by TimoRoth** [comment]
I think it'd be better to test this with the old image still in place, to make sure fixing the issue does not break old geopandas versions.

**Comment by pat-schmitt** [comment]
Ok, I have undone your changes of the test image

**Comment by fmaussion** [comment]
Thanks!! @TimoRoth can you check on the new images?

**Comment by TimoRoth** [comment]
For some reason I can't, any attempt to push leaves me with a server 
error, and going to my repository also presents me with a similar error.

Gonna have to wait until Github fixes itself.

**Comment by pat-schmitt** [comment]
I just saw I have forgotten one fix. Will open another PR.
One test failed in master after merging, but not here at the last commit. Are the new images automatically in place when testing master after a merge or why are there these differences?

**Pull request merged**
