### PR TITLE
Try fixing coveralls

### PR DESCRIPTION
**Pull request by TimoRoth**

### CODE REVIEW

**Comment by fmaussion** [comment]
Good news! Coveralls is communicating with us again (I think this is due to my log out - log in action)

Bad news! We are still at 52% :D

**Comment by TimoRoth** [comment]
I think this is fixed now, just testing around a bit now, will merge when done with that.

**Comment by TimoRoth** [comment]
I _think_ the 76% it reports now are accurate, but I'm not sure how to exactly read the reports it gives. There are lines in red, green, and some marked with uncov.

**Comment by fmaussion** [comment]
Thanks Timo, 76% does seem much more reasonable.

The reports also look better, although some of the red lines are strange (e.g. function definition lines or module level imports are also red), but at least this is something we can work with now.

**Pull request merged**
