### PR TITLE
Add a roadmap for our policy regarding dependencies

### PR DESCRIPTION
**Pull request by fmaussion**
Closes https://github.com/OGGM/oggm/issues/590 

@TimoRoth @alexjarosch this a draft roadmap on how we could handle the dependency problem.

@TimoRoth of course this is a draft and your input is welcome. My objective here is to reduce both your and my maintenance work, and I believe the guidelines here will help a litte.

We can discuss here or on slack what needs to be done to finish this, but as I understand it we are pretty close already.

### CODE REVIEW

**Comment by fmaussion** [comment]
You can see it rendered [here](https://github.com/OGGM/oggm/blob/919bb2b3ac1f6fb193aaa4bac7189872124167af/DEPENDENCIES_ROADMAP.md)

**Comment by alexjarosch** [comment]
Hi guys,
for your situation 5 as well as for general reproducibility as a scientific standard, it is vital to publish a container along with some results from OGGM so that everybody can reproduce it. This is possible as you can nicely store the respective container on github (LFS extension) and thus it will end up in your zenodo doi numbered repo snapshot which will be in your paper.

I think we should establish this as "good practice" when working with OGGM and require that from our users when they publish with OGGM.

Alex

**Comment by fmaussion** [comment]
Thanks to the great work by Timo, I think we are following this roadmap quite closely now. I propose to merge this, and keep it available for future changes.

**Comment by fmaussion** [comment]
Regarding "good practices" I'm working on the documentation right now and will submit a PR shortly

**Pull request merged**
