### PR TITLE
Update test container

### PR DESCRIPTION
**Pull request by TimoRoth**
I'm pretty sure this will break things, and since I pinned pyproj to <2.0 on this one, some other update must have made a mess as well.
If not, it really is all just caused by pyproj in some ways.

### CODE REVIEW

**Comment by fmaussion** [comment]
I'm betting 5 euros on all green!

**Comment by TimoRoth** [comment]
Thing is, on Anaconda(both for 3.6 and 3.7) and Travis-Python 3.7 I'm seeing this breakage:
https://travis-ci.org/OGGM/OGGM-Anaconda/jobs/545222912#L1006
And that is with pyproj pinned to <2.0.

**Comment by fmaussion** [comment]
actually we shouldn't even download these things from our tests (410.4 MiB)

I'll have a look at the VASScaling tests

**Comment by fmaussion** [comment]
OK, let's hope the new test will look different - can you rebase once my pr is merged? 

The mpl test failures are probably unrleated

**Pull request merged**
