### PR TITLE
Added task to get the pointwise catchment area and linear mass balance

### PR DESCRIPTION
**Pull request by MatCast**
- [x] Tests added/passed
- [x] Fully documented
- [x] Entry in `whats-new.rst`

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks! This is looking good. I'll have a more detailed look next week.

**Comment by fmaussion** [comment]
@MatCast this is very good thanks!

in terms of API this is not exactly what I was looking for - I want to hide this under a more general task. If you agree I'll add some changes on top of your PR, ok?

**Comment by MatCast** [comment]
@fmaussion of course go ahead please.

**Comment by MatCast** [comment]
I found a bug in the code which would generate a `ValueError` for some glaciers. I fixed it but let me merge the updated code before merging this into master. Or should i merge it with the corrected API that you had in mind as well?

**Comment by fmaussion** [comment]
@MatCast sorry I missed your previous posts. I think I've changed too much now, and likely my version is buggy as well so I'll try to test it on more glaciers.

I'm thinking a bit bigger now because I also have interest to get more things related to ice thickness in OGGM, I'll add some documentation about this first,  then continue in another PR.

**Comment by fmaussion** [comment]
Thanks @MatCast !

**Pull request merged**
